# Generated by Django 5.0.4 on 2024-04-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='number_of_people',
            field=models.IntegerField(),
        ),
    ]
